### ISSUE TITLE
[REQUEST] Create a tally that shows how many wins/loses a team has.

### ISSUE THREAD

**Issue by Aura89** [Bara20/TroubleinTerroristTown#136] opened 2017-08-07 19:36 UTC
Would it be possible to have TTT create a file that logs each win and loss in total number form? So we can easily either look at that config file, or do some command that'll tell us how many times a team has won?

The reason i ask is, in trying to create a fair TTT server that does not side one side over the other, its hard to figure out exactly how much one side is winning.

This tool would create a system that would allow a server to better fine-tune how much health/armor/costs of items/etc. affect the game.

Let me know if its possible and if it'll be introduced, it'd be greatly appreciated!

**Comment by Bara20** [comment] 2017-08-12 22:18
A mysql version is planned as stats/logging plugin.

Duplicate of #22

**Comment by Bara20** [comment] 2017-08-12 22:19
Duplicate of #22

**Closed by Bara20** 2017-08-12 22:18 UTC
